name: politech_manager
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.3
  http: ^0.13.4
  google_fonts: ^3.0.0
  either_dart: ^0.1.4
  package_info_plus: ^1.4.2
  uuid: 3.0.6
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.2
  open_file: ^3.2.1
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/


