// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBi28GOHQk-0OLiHXP8CI5NqBhbb8b_No',
    appId: '1:172845243028:web:651b771f0dee195e67b281',
    messagingSenderId: '172845243028',
    projectId: 'epcc-manager',
    authDomain: 'epcc-manager.firebaseapp.com',
    storageBucket: 'epcc-manager.appspot.com',
    measurementId: 'G-450GC2KGBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBioy1bGnCtCpQLdG6h9ZxeJ2hah4Pdz14',
    appId: '1:172845243028:android:80043d4e7fe10edd67b281',
    messagingSenderId: '172845243028',
    projectId: 'epcc-manager',
    storageBucket: 'epcc-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX3PZtEpXQD2-pjTT4e4nOVm4d5PjP73M',
    appId: '1:172845243028:ios:74db681077e879a367b281',
    messagingSenderId: '172845243028',
    projectId: 'epcc-manager',
    storageBucket: 'epcc-manager.appspot.com',
    iosClientId: '172845243028-dcqg9b36abkto28ephu616ib6hj2otgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.politechManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX3PZtEpXQD2-pjTT4e4nOVm4d5PjP73M',
    appId: '1:172845243028:ios:74db681077e879a367b281',
    messagingSenderId: '172845243028',
    projectId: 'epcc-manager',
    storageBucket: 'epcc-manager.appspot.com',
    iosClientId: '172845243028-dcqg9b36abkto28ephu616ib6hj2otgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.politechManager',
  );
}
